# configuration.yaml
---
################################################################################
# Home Assistant Main
################################################################################

################################################################################
# Home Assistant Components
################################################################################
default_config:
http: !include http.yaml

################################################################################
# Home Assistant Integrations
# Installed integrations are listed below:
#
#   https://www.home-assistant.io/integrations                                    
#
################################################################################
# binary_sensor: !include_dir_merge_list integrations/binary_sensors/
# group: !include_dir_named integrations/groups/
# spotify: !include integrations/spotify.yaml
spotify:
  client_id: !env_var SPOTIFY_CLIENT_ID
  client_secret: !env_var SPOTIFY_CLIENT_SECRET